### ISSUE TITLE
سلام داداش

### ISSUE THREAD

**Issue by imBlueMan** [teymoorbabayani/quasarwebapplication#1]
از توییتر رفتی؟

**Comment by teymoorbabayani** [comment]
سلام داداش، توییتر سر میزنم ولی توییت نمیکنم، عکس و اینام رو هم تغییر دادم غیر فعال دیده میشه
در خدمتم داداش، از هرجا پیام بدی حتی توییتر بهم میرسه قطعا، کاری باری بود بگو

**Comment by imBlueMan** [comment]
🍻🍻 دمت گرم داداش ، با قدرت ادامه بده
